test: add a test to check command generation with different order
Test output:

```
> go test ./run_test.go
20:19:30.614 DEBUG  Running command: i-dont-exist
20:19:30.614 DEBUG  Engine is not enabled, running command directly in .
20:19:30.616 ERROR  unknown invocation failed in .
20:19:30.649 DEBUG  Skipping var-file optional.tfvars as it does not exist
--- FAIL: TestFilterTerraformExtraArgs (0.06s)
    run_test.go:451:
                Error Trace:    /home/monkeypac/dev/terragrunt/cli/commands/run/run_test.go:451
                Error:          Not equal:
                                expected: []string{"--foo", "bar", "foo"}
                                actual  : []string{"--foo", "-var-file=test.tfvars", "bar", "-var='key=value'", "foo", "-var-file=required.tfvars", "-var-file=/tmp/TestFilterTerraformExtraArgs3197671377/001/3320748883"}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,5 +1,9 @@
                                -([]string) (len=3) {
                                +([]string) (len=7) {
                                  (string) (len=5) "--foo",
                                + (string) (len=21) "-var-file=test.tfvars",
                                  (string) (len=3) "bar",
                                - (string) (len=3) "foo"
                                + (string) (len=16) "-var='key=value'",
                                + (string) (len=3) "foo",
                                + (string) (len=25) "-var-file=required.tfvars",
                                + (string) (len=68) "-var-file=/tmp/TestFilterTerraformExtraArgs3197671377/001/3320748883"
                                 }
                Test:           TestFilterTerraformExtraArgs
FAIL
FAIL    command-line-arguments  0.095s
FAIL
```